# -*- coding: utf-8 -*-
# This Python file uses the following encoding: utf-8

## @file
## @author Willam Seite
##  Esse codigo é protegido pela comunidade
##  de codigo livre pela licença de codigo
##  livre GPL3 e por Deus, pois só Deus sabe
##  o que contece se mudar essa merda
##
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

### from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5 import (
    QtGui,
    uic,
    QtWidgets
)
import backend


#class main(QWidget):
#    def __init__(self):
#        QWidget.__init__(self)


#if __name__ == "__main__":
#    app = QApplication([])
#    window = main()
#    window.show()
#    sys.exit(app.exec_())

## fecha janela
def exit():
    window.close()

## CRIA UMA VARIAVEL GLOBAL E ATRIBUI A ULTIMA PESQUISA FEITA
def getvar(self):
    global xx
    xx = self
    # return xx

########## ADICIONA DADOS DO CEP AO BANCO DE DADOS
def addCep():
    d = xx # preguiça d mudar toda lista
    backend.addCityRec(d['cep'], d['logradouro'], d['complemento'], \
    d['bairro'], d['localidade'], d['uf'], d['ddd'])
    print(xx)

## busca o cep e exibe na tabela do layout
def search(self):
    linha = window.lineEdit.text() ## obtem dados do campo de texto
    linha = linha.strip()
    window.lineEdit.setText('') ## limpa campo 
    if len(linha) == 8:
        d = backend.lambda_handler(linha)  ## uso da api para buscar cep
        if type(d) == str:
            window.label_2.setText("Cep inexistente")
        else:
            data = backend.getInfoByCep(d)
            print(data)
            tablerow = 0
            dd = []
            window.tableWidget.setRowCount(1)
            window.tableWidget.setColumnCount(8)
            window.label_2.setText("Esses sao os dados ")
            for key, value in data.items():
                dd.append(value)
            for i in range(1, 8):
                window.tableWidget.setItem(tablerow, i, QtWidgets.QTableWidgetItem(str(dd[i-1])))
            getvar(data)
            # if 
    else:
        window.label_2.setText("por favor, prencher o CEP corretamente")

#dd = backend.getInfoByCep('32186440')

def showdb(self):
    results = backend.viewDate()
    window.tableWidget.setRowCount(len(results))
    window.tableWidget.setColumnCount(8)
    for i in range(0, len(results)):
        for j in range(0, 8):
            window.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(results[i][j])))
#    self.table.setRowCount(0)

#    for row_number, row_data in enumerate(results):
#        self.table.insetRow(row_number)
#        for colum_number, data in enumerate(row_data):
#            self.table.setItem(row_number, colum_number, QtWidgets.QTableWidgetItem(str(data)))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = uic.loadUi("dialog.ui")
    window.setWindowTitle("Programa :3") 

    backend.cityData() ## se db não estiver criado, ele cria agora
#    window.tableWidget.setColumnWidth(0, 40)
#    window.tableWidget.setColumnWidth(1, 100)
#    window.tableWidget.setColumnWidth(2, 200)
#    window.tableWidget.setColumnWidth(3, 200)
#    window.tableWidget.setColumnWidth(4, 100)
#    window.tableWidget.setColumnWidth(5, 200)
#    window.tableWidget.setColumnWidth(6, 40)
#    window.tableWidget.setColumnWidth(7, 40)


    window.pushButton.clicked.connect(search)
    window.pushButton_2.clicked.connect(exit)
    window.pushButton_3.clicked.connect(showdb)
    window.pushButton_4.clicked.connect(addCep)
    window.show()
    sys.exit(app.exec_())
