# -*- coding: utf-8 -*-
# This Python file uses the following encoding: utf-8

## @file
## @author Willam Seite
##  Esse codigo é protegido pela comunidade
##  de codigo livre pela licença de codigo
##  livre GPL3 e por Deus, pois só Deus sabe
##  o que contece se mudar essa merda
##
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

### from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5 import (
    QtGui,
    uic,
    QtWidgets
)
import backend


#class main(QWidget):
#    def __init__(self):
#        QWidget.__init__(self)


#if __name__ == "__main__":
#    app = QApplication([])
#    window = main()
#    window.show()
#    sys.exit(app.exec_())

## fecha janela
def exit():
    window.close()
def exitF():
    formulario.close()

## CRIA UMA VARIAVEL GLOBAL E ATRIBUI A ULTIMA PESQUISA FEITA

# global xx
# xx = {}
def getvar(self):
    global xx
    xx = self
    # return xx
global cc
cc = True
def check(self = False):
    c = self
    return c
########## ADICIONA DADOS DO CEP AO BANCO DE DADOS
def addForm():
    dictForm = {
    'logradouro' : formulario.lineEdit.text(),
    'complemento' : formulario.lineEdit_2.text(),
    'bairro' : formulario.lineEdit_3.text(),
    'aluguel' : formulario.lineEdit_4.text(),
    'cdCasa' : formulario.lineEdit_5.text(),
    'dono' : formulario.lineEdit_6.text()
    }

    formulario.lineEdit.setText('')
    formulario.lineEdit_2.setText('')
    formulario.lineEdit_3.setText('')
    formulario.lineEdit_4.setText('')
    formulario.lineEdit_5.setText('')
    formulario.lineEdit_6.setText('')
    d = xx # preguiça d mudar toda lista
    backend.addCityRec(d['cep'], dictForm['logradouro'], dictForm['complemento'], dictForm['bairro'], \
        d['localidade'] ,dictForm['aluguel'], dictForm['cdCasa'] ,dictForm['dono'], d['uf'], d['ddd'])
    # for key, value in dictForm.items():
    #     print(value, key )

def getLinha():
    linha = window.lineEdit.text() ## obtem dados do campo de texto
    linha = linha.strip()
    window.lineEdit.setText('') ## limpa campo 
    return linha
### A FUNÇÃO ABAIXO FAZIA A BSUCA DO CEP E EXIBIA NA TABELA 
### PERCEBI QUE ELA ERA INUTIL. 
### VOU DEIXAR  CODIGO AQUI POR QUANTO, TALVEZ DEPOIS EU O REMOVO
# def addCep():
#     # print(linha)
#     linha = window.lineEdit.text() ## obtem dados do campo de texto
#     linha = linha.strip()
#     window.lineEdit.setText('')
#     # linha = getLinha
#     # di = xx
#     if len(linha) == 8:
#         d = backend.lambda_handler(linha)
#         if type(d) == str:
#             window.label_2.setText("Cep inexistente")  ## uso da api para buscar cep 
#         else:
#             data = backend.getInfoByCep(d)
#             getvar(data)
#             # print(data)
#             formulario.show()
#             formulario.pushButton.clicked.connect(addForm)
#             formulario.pushButton_2.clicked.connect(exitF)
#         # else:
#         #     window.label_2.setText("por favor, prencher o CEP corretamente")
#     # elif xx:
#         # formulario.show()
#         # formulario.pushButton.clicked.connect(addForm)
#         # formulario.pushButton_2.clicked.connect(exitF)
#     else:
#         window.label_2.setText("Você precisa digitar um cep primeiro")

## busca o cep e exibe na tabela do layout
def search(self):
    linha = window.lineEdit.text() ## obtem dados do campo de texto
    linha = linha.strip()
    window.lineEdit.setText('')
    # print(linha)
    if len(linha) == 8:
        d = backend.lambda_handler(linha)  ## uso da api para buscar cep
        if type(d) == str:
            window.label_2.setText("Cep inexistente")
        else:
            data = backend.getInfoByCep(d)
            # print(data)
            tablerow = 0
            dd = []
            window.tableWidget.setRowCount(1)
            window.tableWidget.setColumnCount(8)
            window.label_2.setText("Esses sao os dados ")
            for key, value in data.items():
                dd.append(value)
            for i in range(1, 8):
                window.tableWidget.setItem(tablerow, i, QtWidgets.QTableWidgetItem(str(dd[i-1])))
            # getvar(data)
            # data = backend.getInfoByCep(d)
            # getvar(data)
            # print(data)
            formulario.show()
            formulario.pushButton.clicked.connect(addForm)
            formulario.pushButton_2.clicked.connect(exitF)
            cc = check(True)
            # if 
    else:
        window.label_2.setText("por favor, prencher o CEP corretamente")

#dd = backend.getInfoByCep('32186440')
def exitT():
    tabela.close()
def exitTt():
    editar.close()

def deleteD():
    linha = tabela.tableWidget.currentRow()
    tabela.tableWidget.removeRow(linha)
    ids = backend.knowId()
    id = ids[linha][0]
    backend.deleteRec(id)

def saveEdit():
    id = editar.lineEdit.text()
    cep = editar.lineEdit_2.text()
    logr = editar.lineEdit_3.text()
    comp = editar.lineEdit_4.text()
    bairro = editar.lineEdit_5.text()
    localidade = editar.lineEdit_6.text()
    aluguel = editar.lineEdit_7.text()
    codcasa = editar.lineEdit_8.text()
    dono = editar.lineEdit_9.text()
    uf = editar.lineEdit_10.text()
    ddd = editar.lineEdit_11.text()
    print(id)
    backend.updateData(id, cep, logr, comp, bairro, localidade, aluguel, codcasa, dono, uf, ddd )
    showdb()
    editar.close()

def editData():
    linha = tabela.tableWidget.currentRow()
    ids = backend.knowId()
    id = ids[linha][0]
    casa = backend.row(id)
    editar.lineEdit.setText(str(casa[0][0]))
    editar.lineEdit_2.setText(str(casa[0][1]))
    editar.lineEdit_3.setText(str(casa[0][2]))
    editar.lineEdit_4.setText(str(casa[0][3]))
    editar.lineEdit_5.setText(str(casa[0][4]))
    editar.lineEdit_6.setText(str(casa[0][5]))
    editar.lineEdit_7.setText(str(casa[0][6]))
    editar.lineEdit_8.setText(str(casa[0][7]))
    editar.lineEdit_9.setText(str(casa[0][8]))
    editar.lineEdit_10.setText(str(casa[0][9]))
    editar.lineEdit_11.setText(str(casa[0][10]))
    editar.show()
    # print(casa)
    editar.pushButton.clicked.connect(saveEdit)
    editar.pushButton_2.clicked.connect(exitTt)

def showdb():
    tabela.show()
    results = backend.viewDate()
    tabela.tableWidget.setRowCount(len(results))
    tabela.tableWidget.setColumnCount(11)
    for i in range(0, len(results)):
        for j in range(0, 11):
            tabela.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(str(results[i][j])))
    tabela.pushButton_2.clicked.connect(exitT)
    tabela.pushButton_3.clicked.connect(deleteD)
    tabela.pushButton_4.clicked.connect(editData)
#    self.table.setRowCount(0)

#    for row_number, row_data in enumerate(results):
#        self.table.insetRow(row_number)
#        for colum_number, data in enumerate(row_data):
#            self.table.setItem(row_number, colum_number, QtWidgets.QTableWidgetItem(str(data)))



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = uic.loadUi("dialog.ui")
    window.setWindowTitle("Programa :3")
    formulario = uic.loadUi("form.ui")
    tabela = uic.loadUi("table.ui")
    editar = uic.loadUi("edit.ui")

    backend.cityData() ## se db não estiver criado, ele cria agora
#    window.tableWidget.setColumnWidth(0, 40)
#    window.tableWidget.setColumnWidth(1, 100)
#    window.tableWidget.setColumnWidth(2, 200)
#    window.tableWidget.setColumnWidth(3, 200)
#    window.tableWidget.setColumnWidth(4, 100)
#    window.tableWidget.setColumnWidth(5, 200)
#    window.tableWidget.setColumnWidth(6, 40)
#    window.tableWidget.setColumnWidth(7, 40)

    # window.pushButton.clicked.connect(search)
    window.pushButton_2.clicked.connect(exit)
    window.pushButton_3.clicked.connect(showdb)
    window.pushButton_4.clicked.connect(search)
    window.show()
    sys.exit(app.exec_())
