# -*- coding: utf-8 -*-
# This Python file uses the following encoding: utf-8
## @file
## @author Willam Seite
##  Esse codigo é protegido pela comunidade
##  de codigo livre pela licença de codigo
##  livre GPL3 e por Deus, pois só Deus sabe
##  o que contece se mudar essa merda
##
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
### from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5 import QtGui, uic, QtWidgets
import backend

# global ff
# ff = 1
## fecha janela
def exit():
    window.close()
# def exitF():
#     formulario.close()

## CRIA UMA VARIAVEL GLOBAL E ATRIBUI A ULTIMA PESQUISA FEITA
## HOLDER == suporte
def holder(x):
    global xx
    xx = x

def getLinha():
    linha = window.lineEdit.text()  # obtem dados do campo de texto
    linha = linha.strip()
    window.lineEdit.setText('')  # limpa campo
    return linha

### A FUNÇÃO ABAIXO FAZIA A BUSCA DO CEP E EXIBIA NA TABELA
### PERCEBI QUE ELA ERA INUTIL.
### VOU DEIXAR  CODIGO AQUI POR ENQUANTO, TALVEZ DEPOIS EU O REMOVO

# def addCep():
#     # print(linha)
#     linha = window.lineEdit.text() ## obtem dados do campo de texto
#     linha = linha.strip()
#     window.lineEdit.setText('')
#     # linha = getLinha
#     # di = xx
#     if len(linha) == 8:
#         d = backend.lambda_handler(linha)
#         if type(d) == str:
#             window.label_2.setText("Cep inexistente")  ## uso da api para buscar cep
#         else:
#             data = backend.getInfoByCep(d)
#             getvar(data)
#             # print(data)
#             formulario.show()
#             formulario.pushButton.clicked.connect(addForm)
#             formulario.pushButton_2.clicked.connect(exitF)
#         # else:
#         #     window.label_2.setText("por favor, prencher o CEP corretamente")
#     # elif xx:
#         # formulario.show()
#         # formulario.pushButton.clicked.connect(addForm)
#         # formulario.pushButton_2.clicked.connect(exitF)
#     else:
#         window.label_2.setText("Você precisa digitar um cep primeiro")


############### busca o cep e exibe na tabela do layout PRINCIPAL
############### e abre tela com opções para editar e add ao db

def addCasa():
    linha = window.lineEdit.text()  # obtem dados do campo de texto
    linha = linha.strip()
    window.lineEdit.clear()
    
    def getText():
        dictForm = {
            'cep': editar.lineEdit_2.text(),
            'logradouro': editar.lineEdit_3.text(),
            'complemento': editar.lineEdit_4.text(),
            'bairro': editar.lineEdit_5.text(),
            'localidade': editar.lineEdit_6.text(),
            'aluguel': editar.lineEdit_7.text(),
            'cdCasa': editar.lineEdit_8.text(),
            'dono': editar.lineEdit_9.text(),
            'uf': editar.lineEdit_10.text(),
            'ddd': editar.lineEdit_11.text()
        }
        return dictForm
        
    def addData():
        # global ff
        # ff += 1
        dictForm = getText()
        # dictForm = {
        #     'cep' : editar.lineEdit_2.text(),
        #     'logradouro' : editar.lineEdit_3.text(),
        #     'complemento' : editar.lineEdit_4.text(),
        #     'bairro' : editar.lineEdit_5.text(),
        #     'localidade' : editar.lineEdit_6.text(),
        #     'aluguel' : editar.lineEdit_7.text(),
        #     'cdCasa' : editar.lineEdit_8.text(),
        #     'dono' : editar.lineEdit_9.text(),
        #     'uf' : editar.lineEdit_10.text(),
        #     'ddd' : editar.lineEdit_11.text()
        # }

        # formulario.lineEdit.setText('')
        # d = xx # preguiça d mudar toda lista
        # print(ff)
        backend.addCityRec(dictForm['cep'], dictForm['logradouro'], dictForm['complemento'], dictForm['bairro'], \
            dictForm['localidade'] ,dictForm['aluguel'], dictForm['cdCasa'] ,dictForm['dono'], dictForm['uf'], dictForm['ddd'])
        # id = editar.lineEdit.text()
        # print(id)
        # showdb()
        editar.close()

    def exit():
        editar.close()
            
    # print(linha)
    if len(linha) == 8:
        # uso da api para buscar cep
        # seu retorno são alguns dados do cep
        d = backend.lambda_handler(linha)
        if type(d) == str:
            window.label_2.setText("Cep inexistente")
        else:
            
            editar = uic.loadUi("edit.ui")
            # Seleciona e organiza os dados retornados
            data = backend.getInfoByCep(d)
            # print(data)
            tablerow = 0
            dd = []
            window.tableWidget.setRowCount(1)
            window.tableWidget.setColumnCount(7)
            window.label_2.setText("Esses são os dados ")

            for key, value in data.items():
                dd.append(value)
            #     # print(value)
            for i in range(0, 7):
                window.tableWidget.setItem(tablerow, i, QtWidgets.QTableWidgetItem(str(dd[i])))
            # SALVA OS DADOS DA PESQUISA NUMA VAR GLOBAL
            # holder(data)
            # print(data)
            # linha = tabela.tableWidget.currentRow()
            # casa = backend.row(id)
            editar.lineEdit_2.setText(str(dd[0]))
            editar.lineEdit_3.setText(str(dd[1]))
            editar.lineEdit_4.setText(str(dd[2]))
            editar.lineEdit_5.setText(str(dd[3]))
            editar.lineEdit_6.setText(str(dd[4]))
            editar.lineEdit_10.setText(str(dd[5]))
            editar.lineEdit_11.setText(str(dd[6]))
            editar.show()
            editar.pushButton.clicked.connect(addData)
            editar.pushButton_2.clicked.connect(exit)

            # editar.pushButton_2.clicked.connect(exitTt)
            # formulario.pushButton.clicked.connect(addForm)
            # formulario.pushButton_2.clicked.connect(exitF)
    else:
        window.label_2.setText("Por favor, prencher o CEP corretamente")

####### EXIBE BANCO DE DADOS #########################################

def showdb():
    tabela = uic.loadUi("table.ui")
    tabela.setWindowTitle("Dados")
    def exitT():
        tabela.close()

    def deleteD():
        linha = tabela.tableWidget.currentRow()
        tabela.tableWidget.removeRow(linha)
        ids = backend.knowId()
        id = ids[linha][0]
        backend.deleteRec(id)
        
    def editData():
        def exitE():
            editar1.close()
        def saveEdit():
            id = editar1.lineEdit.text()
            dictForm = getText()
            # cep = editar.lineEdit_2.text()
            # logr = editar.lineEdit_3.text()
            # comp = editar.lineEdit_4.text()
            # bairro = editar.lineEdit_5.text()
            # localidade = editar.lineEdit_6.text()
            # aluguel = editar.lineEdit_7.text()
            # codcasa = editar.lineEdit_8.text()
            # dono = editar.lineEdit_9.text()
            # uf = editar.lineEdit_10.text()
            # ddd = editar.lineEdit_11.text()
            # print(id)
            # d = xx
            backend.updateData(id,  dictForm['cep'], dictForm['logradouro'], dictForm['complemento'], dictForm['bairro'],
                            dictForm['localidade'], dictForm['aluguel'], dictForm['cdCasa'], dictForm['dono'], dictForm['uf'], dictForm['ddd'])
            showdb()
            editar1.close()
        
        def getText():
            dictForm = {
                'cep': editar1.lineEdit_2.text(),
                'logradouro': editar1.lineEdit_3.text(),
                'complemento': editar1.lineEdit_4.text(),
                'bairro': editar1.lineEdit_5.text(),
                'localidade': editar1.lineEdit_6.text(),
                'aluguel': editar1.lineEdit_7.text(),
                'cdCasa': editar1.lineEdit_8.text(),
                'dono': editar1.lineEdit_9.text(),
                'uf': editar1.lineEdit_10.text(),
                'ddd': editar1.lineEdit_11.text()
            }
            return dictForm

        tabela.close()
        editar1 = uic.loadUi("edit.ui")
        linha = tabela.tableWidget.currentRow()
        ids = backend.knowId()
        id = ids[linha][0]
        casa = backend.row(id)
        editar1.lineEdit.setText(str(id))
        editar1.lineEdit_2.setText(str(casa[0][1]))
        editar1.lineEdit_3.setText(str(casa[0][2]))
        editar1.lineEdit_4.setText(str(casa[0][3]))
        editar1.lineEdit_5.setText(str(casa[0][4]))
        editar1.lineEdit_6.setText(str(casa[0][5]))
        editar1.lineEdit_7.setText(str(casa[0][6]))
        editar1.lineEdit_8.setText(str(casa[0][7]))
        editar1.lineEdit_9.setText(str(casa[0][8]))
        editar1.lineEdit_10.setText(str(casa[0][9]))
        editar1.lineEdit_11.setText(str(casa[0][10]))
        editar1.show()
        # print(casa)
        editar1.pushButton.clicked.connect(saveEdit)
        editar1.pushButton_2.clicked.connect(exitE)
        
    # def pri():
    #     print(66)

    tabela.show()
    results = backend.viewDate()
    tabela.tableWidget.setRowCount(len(results))
    tabela.tableWidget.setColumnCount(11)
    for i in range(0, len(results)):
        for j in range(0, 11):
            tabela.tableWidget.setItem( i, j, QtWidgets.QTableWidgetItem(str(results[i][j])))
    tabela.pushButton_2.clicked.connect(exitT)
    tabela.pushButton_3.clicked.connect(deleteD)
    tabela.pushButton_4.clicked.connect(editData)

##########################################################################

app = QtWidgets.QApplication(sys.argv)
window = uic.loadUi("dialog.ui")
window.setWindowTitle("Programa :3")
    # formulario = uic.loadUi("form.ui")

backend.cityData()  # se db não estiver criado, ele cria agora

    # window.pushButton.clicked.connect(search)

window.pushButton_2.clicked.connect(exit)
window.pushButton_3.clicked.connect(showdb)
window.pushButton_4.clicked.connect(addCasa)
window.show()
app.exec()
